const fs=require('fs');
const path=require('path');
const {getHistoricalRates}=require('dukascopy-node');
const WebSocket=require('ws');
const START_MS=Date.parse('2025-08-15T00:00:00Z');
const END_MS=Date.parse('2026-08-13T00:00:00Z')-1;
const RAW='trailaris_ephemeral/raw_common'; fs.mkdirSync(RAW,{recursive:true});
const duk={EURUSD:'eurusd',GBPUSD:'gbpusd',USDJPY:'usdjpy',AUDUSD:'audusd',USDCAD:'usdcad',USDCHF:'usdchf',NZDUSD:'nzdusd',EURJPY:'eurjpy',GBPJPY:'gbpjpy',EURGBP:'eurgbp',AUDJPY:'audjpy',CADJPY:'cadjpy',GBPCHF:'gbpchf',XAUUSD:'xauusd',XAGUSD:'xagusd',US100:'usatechidxusd',US500:'usa500idxusd',US30:'usa30idxusd',GER40:'deuidxeur',UK100:'gbridxgbp',JP225:'jpnidxjpy',WTI:'lightcmdusd',BRENT:'brentcmdusd',NATGAS:'gascmdusd'};
const deriv={V75:'R_75',V50:'R_50',V100:'R_100',V25:'R_25',V10:'R_10'};
const coverage={};
function existing(a){try{return fs.statSync(path.join(RAW,a+'.csv')).size>5000}catch{return false}}
async function dukOne(a,id){if(existing(a)){coverage[a]={source:'CACHE',status:'OK'};return}try{const d=await getHistoricalRates({instrument:id,dates:{from:new Date(START_MS),to:new Date(END_MS+1)},timeframe:'m5',format:'json'});const f=fs.createWriteStream(path.join(RAW,a+'.csv'));f.write('timestamp,open,high,low,close,volume\n');let n=0,first=null,last=null;for(const r of d||[]){let t=+r.timestamp;if(t<START_MS||t>END_MS||!Number.isFinite(+r.close))continue;f.write([t,r.open,r.high,r.low,r.close,r.volume??0].join(',')+'\n');n++;if(first===null)first=t;last=t}await new Promise(res=>f.end(res));coverage[a]={source:'DUKASCOPY_RESEARCH_PROXY',rows:n,first,last,status:n>100?'OK':'FAIL'}}catch(e){coverage[a]={source:'DUKASCOPY_RESEARCH_PROXY',rows:0,status:'FAIL',error:String(e)}}}
async function derOne(a,symbol){if(existing(a)){coverage[a]={source:'CACHE',status:'OK'};return}const ws=new WebSocket('wss://ws.binaryws.com/websockets/v3?app_id=1089');let id=1,pending=new Map(),rows=new Map(),pages=0,floor='';await new Promise((res,rej)=>{let t=setTimeout(()=>rej(new Error('open timeout')),15000);ws.once('open',()=>{clearTimeout(t);res()});ws.once('error',rej)});ws.on('message',m=>{let x;try{x=JSON.parse(m.toString())}catch{return};let p=pending.get(x.req_id);if(p){pending.delete(x.req_id);x.error?p.reject(new Error(x.error.message)):p.resolve(x)}});const req=o=>new Promise((res,rej)=>{let rid=id++;pending.set(rid,{resolve:res,reject:rej});ws.send(JSON.stringify({...o,req_id:rid}));setTimeout(()=>{if(pending.has(rid)){pending.delete(rid);rej(new Error('timeout'))}},25000)});try{let end='latest',prev=null;while(pages<80){const x=await req({ticks_history:symbol,end,style:'candles',granularity:300,count:5000,adjust_start_time:1});const cs=x.candles||[];if(!cs.length){floor='EMPTY';break}const eps=cs.map(c=>+c.epoch).filter(Number.isFinite),earliest=Math.min(...eps);for(const c of cs){let t=(+c.epoch)*1000;if(t>=START_MS&&t<=END_MS)rows.set(t,[t,c.open,c.high,c.low,c.close,0])}pages++;if(earliest*1000<=START_MS){floor='REQUESTED_START_REACHED';break}if(prev!==null&&earliest>=prev){floor='PROVIDER_HISTORY_FLOOR';break}prev=earliest;end=earliest-1}}
catch(e){floor='ERROR:'+String(e)}finally{try{ws.close()}catch{}}const arr=[...rows.values()].sort((x,y)=>x[0]-y[0]);const f=fs.createWriteStream(path.join(RAW,a+'.csv'));f.write('timestamp,open,high,low,close,volume\n');for(const r of arr)f.write(r.join(',')+'\n');await new Promise(res=>f.end(res));coverage[a]={source:'DERIV_OFFICIAL',rows:arr.length,first:arr.length?arr[0][0]:null,last:arr.length?arr.at(-1)[0]:null,pages,floor,status:arr.length>100?'OK':'FAIL'};}
async function pool(entries,fn,n){let i=0;await Promise.all(Array.from({length:n},async()=>{while(true){let j=i++;if(j>=entries.length)return;await fn(...entries[j])}}))}
(async()=>{await Promise.all([pool(Object.entries(duk),dukOne,8),pool(Object.entries(deriv),derOne,5)]);fs.writeFileSync('trailaris_ephemeral/coverage_common_node.json',JSON.stringify(coverage,null,2));console.log(JSON.stringify(Object.fromEntries(Object.entries(coverage).map(([k,v])=>[k,v.rows||v.status])),null,2))})();
