#!/usr/bin/env node
const fs=require('fs'),path=require('path');const {getHistoricalRates}=require('dukascopy-node');
function arg(n,d=null){const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d}
const manifest=arg('--manifest'),outdir=arg('--outdir','raw_additions'),START=new Date(arg('--start','2024-12-23T00:00:00Z')),END=new Date(arg('--end','2025-07-21T00:00:00Z')),concurrency=Number(arg('--concurrency','4'));if(!manifest)throw new Error('--manifest required');if(!(START<END))throw new Error('invalid start/end');fs.mkdirSync(outdir,{recursive:true});
const STARTMS=START.getTime(),ENDMS=END.getTime();const rowsIn=fs.readFileSync(manifest,'utf8').trim().split(/\r?\n/).slice(1).map(x=>{const [instrument_id,canonical_instrument,provider_name]=x.split('\t');return {instrument_id,canonical_instrument,provider_name}});const evidence=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function valid(o,h,l,c){return[o,h,l,c].every(Number.isFinite)&&h>=Math.max(o,c)&&l<=Math.min(o,c)&&h>=l}function file(a){return path.join(outdir,a+'_M1_normalized.csv')}
async function write(a,rr){const f=fs.createWriteStream(file(a));f.write('timestamp,open,high,low,close,bid,ask,spread,volume,source,asset\n');for(const r of rr)f.write(r.join(',')+'\n');await new Promise(res=>f.end(res))}
async function one(x){let last='';for(let attempt=1;attempt<=4;attempt++){try{const d=await getHistoricalRates({instrument:x.instrument_id,dates:{from:START,to:END},timeframe:'m1',format:'json',priceType:'bid',batchSize:10,pauseBetweenBatchesMs:250});const seen=new Set(),rr=[];let invalid=0,dupes=0;for(const b of d||[]){const t=+b.timestamp;if(!Number.isFinite(t)||t<STARTMS||t>=ENDMS)continue;if(seen.has(t)){dupes++;continue}seen.add(t);const o=+b.open,h=+b.high,l=+b.low,c=+b.close;if(!valid(o,h,l,c)){invalid++;continue}rr.push([new Date(t).toISOString(),o,h,l,c,c,'','',b.volume??0,'DUKASCOPY_EXACT_INDEPENDENT_RESEARCH_PROXY',x.canonical_instrument])}rr.sort((a,b)=>a[0].localeCompare(b[0]));const first=rr.length?new Date(rr[0][0]):null,lastTs=rr.length?new Date(rr.at(-1)[0]):null;const coverage=!!first&&!!lastTs&&first<=new Date(STARTMS+3*86400000)&&lastTs>=new Date(ENDMS-4*86400000);const ok=rr.length>=1000&&coverage&&invalid===0&&dupes===0;if(ok)await write(x.canonical_instrument,rr);evidence.push({...x,rows:rr.length,invalid_ohlc:invalid,duplicate_timestamps:dupes,first:first?first.toISOString():'',last:lastTs?lastTs.toISOString():'',full_window_coverage:coverage,status:ok?'PASS':'FAIL',file:ok?file(x.canonical_instrument):'',attempt});if(ok)return;evidence.pop();last=`coverage_or_integrity rows=${rr.length} invalid=${invalid} dupes=${dupes}`;}catch(e){last=String(e)}await sleep(900*attempt)}evidence.push({...x,rows:0,invalid_ohlc:0,duplicate_timestamps:0,full_window_coverage:false,status:'FAIL',file:'',attempt:4,error:last})}
async function pool(){let i=0;await Promise.all(Array.from({length:concurrency},async()=>{while(true){const j=i++;if(j>=rowsIn.length)return;await one(rowsIn[j]);await sleep(250)}}))}
(async()=>{await pool();const pass=evidence.filter(x=>x.status==='PASS').length;fs.writeFileSync(path.join(outdir,'ACQUISITION_EVIDENCE_ADDITIONS.json'),JSON.stringify({start:START.toISOString(),end_exclusive:END.toISOString(),assets_scheduled:rowsIn.length,assets_pass:pass,evidence},null,2));console.log(JSON.stringify({assets_scheduled:rowsIn.length,assets_pass:pass,failed:evidence.filter(x=>x.status!=='PASS').map(x=>x.canonical_instrument)},null,2));if(pass!==rowsIn.length)process.exitCode=2;})();
