#!/usr/bin/env node
const fs=require('fs'),path=require('path');const {getHistoricalRates}=require('dukascopy-node');
function arg(n,d=null){const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d}
const manifest=arg('--manifest'),outdir=arg('--outdir','raw_additions'),START=new Date(arg('--start','2024-12-23T00:00:00Z')),END=new Date(arg('--end','2025-07-21T00:00:00Z')),concurrency=Number(arg('--concurrency','4')),chunkDays=Number(arg('--chunk-days','28'));if(!manifest)throw new Error('--manifest required');if(!(START<END))throw new Error('invalid start/end');fs.mkdirSync(outdir,{recursive:true});
const STARTMS=START.getTime(),ENDMS=END.getTime();const rowsIn=fs.readFileSync(manifest,'utf8').trim().split(/\r?\n/).slice(1).map(x=>{const [instrument_id,canonical_instrument,provider_name]=x.split('\t');return {instrument_id,canonical_instrument,provider_name}});const evidence=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function valid(o,h,l,c){return[o,h,l,c].every(Number.isFinite)&&h>=Math.max(o,c)&&l<=Math.min(o,c)&&h>=l}function file(a){return path.join(outdir,a+'_M1_normalized.csv')}
async function write(a,rr){const f=fs.createWriteStream(file(a));f.write('timestamp,open,high,low,close,bid,ask,spread,volume,source,asset\n');for(const r of rr)f.write(r.join(',')+'\n');await new Promise(res=>f.end(res))}
function chunks(){const out=[];let s=STARTMS;const step=Math.max(1,chunkDays)*86400000;while(s<ENDMS){const e=Math.min(ENDMS,s+step);out.push([new Date(s),new Date(e)]);s=e}return out}
async function getChunk(instrument,from,to){let err='';for(let attempt=1;attempt<=4;attempt++){try{return await getHistoricalRates({instrument,dates:{from,to},timeframe:'m1',format:'json',priceType:'bid',batchSize:10,pauseBetweenBatchesMs:180})}catch(e){err=String(e);await sleep(700*attempt)}}throw new Error(err)}
function mergeBars(map,d,x,counters){for(const b of d||[]){counters.total++;const t=+b.timestamp;if(!Number.isFinite(t)||t<STARTMS||t>=ENDMS)continue;const o=+b.open,h=+b.high,l=+b.low,c=+b.close;if(!valid(o,h,l,c)){counters.invalid++;continue}const sig=[o,h,l,c,+b.volume||0].join('|');if(map.has(t)){counters.dupes++;if(map.get(t).sig!==sig)counters.conflicts++;continue}map.set(t,{sig,row:[new Date(t).toISOString(),o,h,l,c,c,'','',b.volume??0,'DUKASCOPY_EXACT_INDEPENDENT_RESEARCH_PROXY',x.canonical_instrument]})}}
async function one(x){let last='';for(let attempt=1;attempt<=3;attempt++){try{const map=new Map(),counters={invalid:0,dupes:0,conflicts:0,total:0};let chunkCount=0;for(const [from,to] of chunks()){mergeBars(map,await getChunk(x.instrument_id,from,to),x,counters);chunkCount++;await sleep(60)}
      // Overlap probes are provider-normalization only. All returned rows are clipped
      // back to the frozen [START, END) interval before entering the research estate.
      const headEnd=new Date(Math.min(ENDMS,STARTMS+14*86400000));
      const tailStart=new Date(Math.max(STARTMS,ENDMS-14*86400000));
      const broadTailStart=new Date(Math.max(STARTMS,ENDMS-75*86400000));
      const broadTailEnd=new Date(ENDMS+7*86400000);
      mergeBars(map,await getChunk(x.instrument_id,START,headEnd),x,counters);
      mergeBars(map,await getChunk(x.instrument_id,tailStart,END),x,counters);
      mergeBars(map,await getChunk(x.instrument_id,broadTailStart,broadTailEnd),x,counters);
      const rr=[...map.entries()].sort((a,b)=>a[0]-b[0]).map(v=>v[1].row);const first=rr.length?new Date(rr[0][0]):null,lastTs=rr.length?new Date(rr.at(-1)[0]):null;const coverage=!!first&&!!lastTs&&first<=new Date(STARTMS+3*86400000)&&lastTs>=new Date(ENDMS-4*86400000);const ok=rr.length>=1000&&coverage&&counters.invalid===0&&counters.conflicts===0;if(ok)await write(x.canonical_instrument,rr);const ev={...x,rows:rr.length,total_provider_rows:counters.total,invalid_ohlc:counters.invalid,duplicate_timestamps_deduplicated:counters.dupes,conflicting_duplicates:counters.conflicts,first:first?first.toISOString():'',last:lastTs?lastTs.toISOString():'',full_window_coverage:coverage,status:ok?'PASS':'FAIL',file:ok?file(x.canonical_instrument):'',attempt,chunk_days:chunkDays,chunks_requested:chunkCount,boundary_probes:3,broad_terminal_probe_days:75,broad_terminal_probe_forward_days:7,normalization:'DATE_SHARDED_PLUS_HEAD_TAIL_AND_BROAD_TERMINAL_OVERLAP__TIMESTAMP_DEDUP__CONFLICTS_FATAL'};if(ok){evidence.push(ev);return}last=JSON.stringify(ev);}catch(e){last=String(e)}await sleep(1000*attempt)}evidence.push({...x,rows:0,full_window_coverage:false,status:'FAIL',file:'',attempt:3,error:last,chunk_days:chunkDays})}
async function pool(){let i=0;await Promise.all(Array.from({length:concurrency},async()=>{while(true){const j=i++;if(j>=rowsIn.length)return;await one(rowsIn[j]);await sleep(150)}}))}
(async()=>{await pool();const pass=evidence.filter(x=>x.status==='PASS').length;fs.writeFileSync(path.join(outdir,'ACQUISITION_EVIDENCE_ADDITIONS.json'),JSON.stringify({start:START.toISOString(),end_exclusive:END.toISOString(),assets_scheduled:rowsIn.length,assets_pass:pass,evidence,normalization:'DATE_SHARDED_PROVIDER_PULLS_PLUS_HEAD_TAIL_AND_BROAD_TERMINAL_PROBES; ALL ROWS CLIPPED TO FROZEN WINDOW; OVERLAPS DEDUPLICATED; CONFLICTS FATAL'},null,2));console.log(JSON.stringify({assets_scheduled:rowsIn.length,assets_pass:pass,failed:evidence.filter(x=>x.status!=='PASS').map(x=>({asset:x.canonical_instrument,error:x.error||'',last:x.last||''}))},null,2));if(pass!==rowsIn.length)process.exitCode=2;})();
