#!/usr/bin/env node
const fs=require('fs'),path=require('path');
const {getHistoricalRates}=require('dukascopy-node');
const WebSocket=require('ws');
function arg(n,d=null){const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d}
const START=new Date(arg('--start','2024-12-23T00:00:00Z'));
const END=new Date(arg('--end','2025-07-21T00:00:00Z')); // exclusive
const RAW=arg('--outdir','raw_core');fs.mkdirSync(RAW,{recursive:true});
if(!(START<END))throw new Error('invalid start/end');
const START_MS=START.getTime(),END_MS=END.getTime()-1;
const duk={EURUSD:'eurusd',GBPUSD:'gbpusd',USDJPY:'usdjpy',AUDUSD:'audusd',USDCAD:'usdcad',USDCHF:'usdchf',NZDUSD:'nzdusd',EURJPY:'eurjpy',GBPJPY:'gbpjpy',EURGBP:'eurgbp',AUDJPY:'audjpy',CADJPY:'cadjpy',GBPCHF:'gbpchf',XAUUSD:'xauusd',XAGUSD:'xagusd',US100:'usatechidxusd',US500:'usa500idxusd',US30:'usa30idxusd',GER40:'deuidxeur',UK100:'gbridxgbp',JP225:'jpnidxjpy',WTI:'lightcmdusd',BRENT:'brentcmdusd',NATGAS:'gascmdusd'};
const deriv={V75:'R_75',V50:'R_50',V100:'R_100',V25:'R_25',V10:'R_10'};
const evidence=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function outfile(asset){return path.join(RAW,asset+'_M1_normalized.csv')}
function validBar(o,h,l,c){return [o,h,l,c].every(Number.isFinite)&&h>=Math.max(o,c)&&l<=Math.min(o,c)&&h>=l}
async function writeRows(asset,rows){const f=fs.createWriteStream(outfile(asset));f.write('timestamp,open,high,low,close,bid,ask,spread,volume,source,asset\n');for(const r of rows)f.write(r.join(',')+'\n');await new Promise(res=>f.end(res));}
function coverage(asset,provider,source,rows,extra={}){const first=rows.length?new Date(rows[0][0]):null,last=rows.length?new Date(rows.at(-1)[0]):null;const ok=rows.length>=1000&&first&&last&&first<=new Date(START_MS+3*86400000)&&last>=new Date(END_MS-4*86400000);evidence.push({instrument_id:provider,canonical_instrument:asset,provider_name:source,rows:rows.length,first:first?first.toISOString():'',last:last?last.toISOString():'',full_window_coverage:!!ok,status:ok?'PASS':'FAIL',file:ok?outfile(asset):'',...extra});return ok}
async function dukOne(asset,id){let err='';for(let attempt=1;attempt<=4;attempt++){try{const d=await getHistoricalRates({instrument:id,dates:{from:START,to:END},timeframe:'m1',format:'json',priceType:'bid',batchSize:10,pauseBetweenBatchesMs:250});const seen=new Set(),rows=[];let invalid=0,dupes=0;for(const b of d||[]){const t=+b.timestamp;if(!Number.isFinite(t)||t<START_MS||t>END_MS)continue;if(seen.has(t)){dupes++;continue}seen.add(t);const o=+b.open,h=+b.high,l=+b.low,c=+b.close;if(!validBar(o,h,l,c)){invalid++;continue}rows.push([new Date(t).toISOString(),o,h,l,c,c,'','',b.volume??0,'DUKASCOPY_OFFICIAL_M1_BID_RESEARCH_PROXY',asset])}rows.sort((a,b)=>a[0].localeCompare(b[0]));const ok=coverage(asset,id,'DUKASCOPY_OFFICIAL_M1_BID_RESEARCH_PROXY',rows,{attempt,invalid_ohlc:invalid,duplicate_timestamps:dupes});if(ok&&invalid===0&&dupes===0){await writeRows(asset,rows);return}if(ok){evidence.pop()}err=`coverage_or_integrity rows=${rows.length} invalid=${invalid} dupes=${dupes}`;}catch(e){err=String(e)}await sleep(1200*attempt)}evidence.push({instrument_id:id,canonical_instrument:asset,provider_name:'DUKASCOPY_OFFICIAL_M1_BID_RESEARCH_PROXY',rows:0,full_window_coverage:false,status:'FAIL',file:'',error:err});}
async function derOne(asset,symbol){let ws;try{ws=new WebSocket('wss://ws.binaryws.com/websockets/v3?app_id=1089');let id=1,pending=new Map(),rows=new Map(),pages=0,floor='';await new Promise((res,rej)=>{const t=setTimeout(()=>rej(new Error('open timeout')),15000);ws.once('open',()=>{clearTimeout(t);res()});ws.once('error',rej)});ws.on('message',m=>{let x;try{x=JSON.parse(m.toString())}catch{return};const p=pending.get(x.req_id);if(p){pending.delete(x.req_id);x.error?p.reject(new Error(x.error.message)):p.resolve(x)}});const req=o=>new Promise((res,rej)=>{const rid=id++;pending.set(rid,{resolve:res,reject:rej});ws.send(JSON.stringify({...o,req_id:rid}));setTimeout(()=>{if(pending.has(rid)){pending.delete(rid);rej(new Error('timeout'))}},30000)});let end=Math.floor(END_MS/1000),prev=null;while(pages<140){const x=await req({ticks_history:symbol,end,style:'candles',granularity:60,count:5000,adjust_start_time:1});const cs=x.candles||[];if(!cs.length){floor='EMPTY';break}const eps=cs.map(c=>+c.epoch).filter(Number.isFinite),earliest=Math.min(...eps);for(const c of cs){const t=(+c.epoch)*1000;if(t>=START_MS&&t<=END_MS){const o=+c.open,h=+c.high,l=+c.low,cl=+c.close;if(validBar(o,h,l,cl))rows.set(t,[new Date(t).toISOString(),o,h,l,cl,'','','',0,'DERIV_OFFICIAL_M1_CANDLES',asset])}}pages++;if(earliest*1000<=START_MS){floor='REQUESTED_START_REACHED';break}if(prev!==null&&earliest>=prev){floor='PROVIDER_HISTORY_FLOOR';break}prev=earliest;end=earliest-1}const arr=[...rows.entries()].sort((a,b)=>a[0]-b[0]).map(x=>x[1]);const ok=coverage(asset,symbol,'DERIV_OFFICIAL_M1_CANDLES',arr,{pages,floor});if(ok)await writeRows(asset,arr);}catch(e){evidence.push({instrument_id:symbol,canonical_instrument:asset,provider_name:'DERIV_OFFICIAL_M1_CANDLES',rows:0,full_window_coverage:false,status:'FAIL',file:'',error:String(e)})}finally{try{ws&&ws.close()}catch{}}}
async function pool(entries,fn,n){let i=0;await Promise.all(Array.from({length:n},async()=>{while(true){const j=i++;if(j>=entries.length)return;await fn(...entries[j]);await sleep(300)}}))}
(async()=>{await Promise.all([pool(Object.entries(duk),dukOne,4),pool(Object.entries(deriv),derOne,5)]);const pass=evidence.filter(x=>x.status==='PASS').length;fs.writeFileSync(path.join(RAW,'ACQUISITION_EVIDENCE_CORE.json'),JSON.stringify({start:START.toISOString(),end_exclusive:END.toISOString(),assets_scheduled:29,assets_pass:pass,evidence},null,2));console.log(JSON.stringify({assets_scheduled:29,assets_pass:pass},null,2));if(pass!==29)process.exitCode=2;})();
