#!/usr/bin/env node
const fs=require('fs'),path=require('path');const WebSocket=require('ws');
function arg(n,d=null){const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d}
const START=new Date(arg('--start','2024-11-18T00:00:00Z')),END=new Date(arg('--end','2025-06-16T00:00:00Z')),OUT=arg('--outdir','raw34'),PACE_MS=Number(arg('--pace-ms','1300'));fs.mkdirSync(OUT,{recursive:true});
const ITEMS={V75:'R_75',V50:'R_50',V100:'R_100',V25:'R_25',V10:'R_10'},S=START.getTime(),E=END.getTime();const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function valid(o,h,l,c){return[o,h,l,c].every(Number.isFinite)&&h>=Math.max(o,c)&&l<=Math.min(o,c)&&h>=l}
function openWs(){return new Promise((resolve,reject)=>{const ws=new WebSocket('wss://ws.binaryws.com/websockets/v3?app_id=1089');const t=setTimeout(()=>reject(new Error('open timeout')),15000);ws.once('open',()=>{clearTimeout(t);resolve(ws)});ws.once('error',reject)})}
async function client(){const ws=await openWs();let rid=1;const p=new Map();ws.on('message',m=>{let x;try{x=JSON.parse(m.toString())}catch{return};const z=p.get(x.req_id);if(!z)return;p.delete(x.req_id);x.error?z.reject(new Error(`${x.error.code||''}:${x.error.message||''}`)):z.resolve(x)});const req=o=>new Promise((resolve,reject)=>{const id=rid++;p.set(id,{resolve,reject});ws.send(JSON.stringify({...o,req_id:id}));setTimeout(()=>{if(p.has(id)){p.delete(id);reject(new Error('request timeout'))}},30000)});return {ws,req}}
async function one(asset,symbol){const {ws,req}=await client();const map=new Map();let invalid=0,dupes=0,conflicts=0,requests=0,rateLimitBackoffs=0;try{const chunk=3*86400000;for(let s=S;s<E;s+=chunk){const e=Math.min(E,s+chunk);let x=null,err='';for(let a=1;a<=12;a++){try{x=await req({ticks_history:symbol,start:Math.floor(s/1000),end:Math.floor((e-1)/1000),style:'candles',granularity:60,adjust_start_time:1});break}catch(z){err=String(z);if(err.includes('RateLimit')){rateLimitBackoffs++;await sleep(30000)}else await sleep(Math.min(5000,750*a))}}if(!x)throw new Error(`chunk ${new Date(s).toISOString()} failed ${err}`);requests++;for(const c of x.candles||[]){const t=(+c.epoch)*1000;if(!Number.isFinite(t)||t<S||t>=E)continue;const o=+c.open,h=+c.high,l=+c.low,cl=+c.close;if(!valid(o,h,l,cl)){invalid++;continue}const sig=[o,h,l,cl].join('|');if(map.has(t)){dupes++;if(map.get(t).sig!==sig)conflicts++;continue}map.set(t,{sig,row:[new Date(t).toISOString(),o,h,l,cl,'','','',0,'DERIV_OFFICIAL_M1_CANDLES',asset]})}await sleep(PACE_MS)}
 const rows=[...map.entries()].sort((a,b)=>a[0]-b[0]).map(v=>v[1].row),first=rows.length?new Date(rows[0][0]):null,last=rows.length?new Date(rows.at(-1)[0]):null;const coverage=!!first&&!!last&&first<=new Date(S+86400000)&&last>=new Date(E-2*86400000);const ok=rows.length>=1000&&coverage&&invalid===0&&conflicts===0;if(ok){const f=fs.createWriteStream(path.join(OUT,asset+'_M1_normalized.csv'));f.write('timestamp,open,high,low,close,bid,ask,spread,volume,source,asset\n');for(const r of rows)f.write(r.join(',')+'\n');await new Promise(res=>f.end(res))}return {instrument_id:symbol,canonical_instrument:asset,provider_name:'DERIV_OFFICIAL_M1_CANDLES',rows:rows.length,first:first?first.toISOString():'',last:last?last.toISOString():'',full_window_coverage:coverage,status:ok?'PASS':'FAIL',file:ok?path.join(OUT,asset+'_M1_normalized.csv'):'',requests,chunk_days:3,pace_ms:PACE_MS,rate_limit_backoffs:rateLimitBackoffs,invalid_ohlc:invalid,duplicate_timestamps_deduplicated:dupes,conflicting_duplicates:conflicts,request_semantics:'EXPLICIT_START_END_3DAY_CANDLE_CHUNKS__NO_SUBSCRIBE_FIELD__SEQUENTIAL_PACED_WITH_RATE_LIMIT_BACKOFF'};}finally{try{ws.close()}catch{}}}
(async()=>{const evidence=[];for(const [a,s] of Object.entries(ITEMS)){try{const r=await one(a,s);evidence.push(r);console.log(JSON.stringify(r))}catch(e){const r={instrument_id:s,canonical_instrument:a,provider_name:'DERIV_OFFICIAL_M1_CANDLES',rows:0,full_window_coverage:false,status:'FAIL',file:'',error:String(e)};evidence.push(r);console.log(JSON.stringify(r));await sleep(5000)}}evidence.sort((a,b)=>a.canonical_instrument.localeCompare(b.canonical_instrument));const out={state:'INDEPENDENT_DERIV_SYNTHETIC_RECOVERY',start:START.toISOString(),end_exclusive:END.toISOString(),assets_scheduled:5,assets_pass:evidence.filter(x=>x.status==='PASS').length,evidence,execution_topology:'FIVE_EXACT_SYMBOLS_SEQUENTIAL__PACED_HISTORY_REQUESTS'};fs.writeFileSync(path.join(OUT,'DERIV_RECOVERY_EVIDENCE.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({assets_scheduled:5,assets_pass:out.assets_pass},null,2));if(out.assets_pass!==5)process.exitCode=2})();
