const fs=require('fs'),path=require('path');
const {getHistoricalRates}=require('dukascopy-node');
const WebSocket=require('ws');
const START_MS=Date.parse('2026-01-19T00:00:00Z');
const END_MS=Date.parse('2026-08-15T00:00:00Z')-1;
const RAW='trailaris_longcycle/raw_m1';fs.mkdirSync(RAW,{recursive:true});
const duk={EURUSD:'eurusd',GBPUSD:'gbpusd',USDJPY:'usdjpy',AUDUSD:'audusd',USDCAD:'usdcad',USDCHF:'usdchf',NZDUSD:'nzdusd',EURJPY:'eurjpy',GBPJPY:'gbpjpy',EURGBP:'eurgbp',AUDJPY:'audjpy',CADJPY:'cadjpy',GBPCHF:'gbpchf',XAUUSD:'xauusd',XAGUSD:'xagusd',US100:'usatechidxusd',US500:'usa500idxusd',US30:'usa30idxusd',GER40:'deuidxeur',UK100:'gbridxgbp',JP225:'jpnidxjpy',WTI:'lightcmdusd',BRENT:'brentcmdusd',NATGAS:'gascmdusd'};
const deriv={V75:'R_75',V50:'R_50',V100:'R_100',V25:'R_25',V10:'R_10'};
const coverage={};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function writeRows(asset,rows){const f=fs.createWriteStream(path.join(RAW,asset+'_M1_normalized.csv'));f.write('timestamp,open,high,low,close,bid,ask,spread,volume,source,asset\n');for(const r of rows)f.write(r.join(',')+'\n');return new Promise(res=>f.end(res));}
async function dukOne(asset,id){let lastErr='';for(let attempt=1;attempt<=4;attempt++){try{const d=await getHistoricalRates({instrument:id,dates:{from:new Date(START_MS),to:new Date(END_MS+1)},timeframe:'m1',format:'json',priceType:'bid'});const rows=[];for(const b of d||[]){let t=+b.timestamp;if(t<START_MS||t>END_MS||!Number.isFinite(+b.close))continue;rows.push([new Date(t).toISOString(),b.open,b.high,b.low,b.close,b.close,'','',b.volume??0,'DUKASCOPY_OFFICIAL_M1_BID_RESEARCH_PROXY',asset]);}await writeRows(asset,rows);coverage[asset]={source:'DUKASCOPY_OFFICIAL_M1_BID_RESEARCH_PROXY',rows:rows.length,first:rows.length?rows[0][0]:null,last:rows.length?rows.at(-1)[0]:null,status:rows.length>100?'OK':'FAIL',attempt};return;}catch(e){lastErr=String(e);await sleep(3000*attempt);}}coverage[asset]={source:'DUKASCOPY_OFFICIAL_M1_BID_RESEARCH_PROXY',rows:0,status:'FAIL',error:lastErr};}
async function derOne(asset,symbol){const ws=new WebSocket('wss://ws.binaryws.com/websockets/v3?app_id=1089');let id=1,pending=new Map(),rows=new Map(),pages=0,floor='';await new Promise((res,rej)=>{let t=setTimeout(()=>rej(new Error('open timeout')),15000);ws.once('open',()=>{clearTimeout(t);res()});ws.once('error',rej)});ws.on('message',m=>{let x;try{x=JSON.parse(m.toString())}catch{return};let p=pending.get(x.req_id);if(p){pending.delete(x.req_id);x.error?p.reject(new Error(x.error.message)):p.resolve(x)}});const req=o=>new Promise((res,rej)=>{let rid=id++;pending.set(rid,{resolve:res,reject:rej});ws.send(JSON.stringify({...o,req_id:rid}));setTimeout(()=>{if(pending.has(rid)){pending.delete(rid);rej(new Error('timeout'))}},30000)});try{let end=Math.floor(END_MS/1000),prev=null;while(pages<100){const x=await req({ticks_history:symbol,end,style:'candles',granularity:60,count:5000,adjust_start_time:1});const cs=x.candles||[];if(!cs.length){floor='EMPTY';break}const eps=cs.map(c=>+c.epoch).filter(Number.isFinite),earliest=Math.min(...eps);for(const c of cs){let t=(+c.epoch)*1000;if(t>=START_MS&&t<=END_MS)rows.set(t,[new Date(t).toISOString(),c.open,c.high,c.low,c.close,'','','',0,'DERIV_OFFICIAL_M1_CANDLES',asset])}pages++;if(earliest*1000<=START_MS){floor='REQUESTED_START_REACHED';break}if(prev!==null&&earliest>=prev){floor='PROVIDER_HISTORY_FLOOR';break}prev=earliest;end=earliest-1}}catch(e){floor='ERROR:'+String(e)}finally{try{ws.close()}catch{}}const arr=[...rows.entries()].sort((a,b)=>a[0]-b[0]).map(x=>x[1]);await writeRows(asset,arr);coverage[asset]={source:'DERIV_OFFICIAL_M1_CANDLES',rows:arr.length,first:arr.length?arr[0][0]:null,last:arr.length?arr.at(-1)[0]:null,pages,floor,status:arr.length>100?'OK':'FAIL'};}
async function pool(entries,fn,n,between=0){let i=0;await Promise.all(Array.from({length:n},async()=>{while(true){let j=i++;if(j>=entries.length)return;await fn(...entries[j]);if(between)await sleep(between)}}))}
(async()=>{await Promise.all([pool(Object.entries(duk),dukOne,2,1200),pool(Object.entries(deriv),derOne,5)]);fs.writeFileSync('trailaris_longcycle/coverage_m1_node.json',JSON.stringify(coverage,null,2));console.log(JSON.stringify(coverage,null,2));if(Object.values(coverage).some(x=>x.status!=='OK'))process.exitCode=2;})();